### ISSUE TITLE
v2.0 Tracking Issue

### ISSUE THREAD

**Issue by rtholmes** [ubccpsc/classy#193]
This is just so I can keep track of prioritizing v2 work (checkboxes, but issues are ranked by priority):

- [x] #138: add secret to webhook (get checking in there, even if it isn't enabled)
- [x] #179: team lookup is slow
- [x] #163: cached results is counting as a request
- [x] #206: improve queue robustness on docker restart
- [x] #154: add info button to result view
- [x] #205: Add DB sanity checking
