### ISSUE TITLE
SDMM v1.0 tracking issue

### ISSUE THREAD

**Issue by rtholmes** [ubccpsc/classy#27]
Features that are different for SDMM than 310 that need to be supported through DI:

- [x] Students need to be created w/o a ClassList (e.g., GitHub login should accept any valid OAuth session, although TAs should not be created as students but as admins).

- [x] Getting status needs to work.

- [x] Students need to be able to advance their status automatically.

- [x] Students need to be able to provision their repos automatically.

- [x] There should be no default deliverable. AutoTest should require a `delivId` for any bot invocation. 

- [x] `SDMMRoutesSpec` have some `statusCode` changes that should be fixed.

- [x] `AutoTestRoutes` is mostly filled with mock implementations. 

- [x] SDMM frontend will need to be updated to react to above change where 400s are returned for unusual circumstances.

- [x] Update advancement threshold to 80 or 90%

- [x] Check team formation functionality.

- [x] Test delay not being enforced
