### ISSUE TITLE
310 v1.0 tracking issue

### ISSUE THREAD

**Issue by rtholmes** [ubccpsc/classy#29]
This will slowly accumulate minor issues that will interfere with a 310 rollout. This issue exists so small things won't get forgotten.

- [x] `Frontend::App::getGithubCredentials` is hardcoded to github.com

- [x] #25 Student grade view

- [x] #26 Student team formation

- [x] `AuthRoutes::authCallback(..)` always creates new users (aka good for SDMM, bad for 310)

- [x] #76 Repo provisioning

- [x] Enforce deliverable deadlines for grade updates.
