### ISSUE TITLE
310 v1.1 tracking issue

### ISSUE THREAD

**Issue by rtholmes** [ubccpsc/classy#90]
- [x] Team formation is somewhat ugly

- [x] #23 TAs need the dashboard

- [x] Render single-student teams in admintab

- [x] Add repositories list item for provisioned repos on student frontend.

- [x] Don't show tables on student frontend that have no rows.

**Comment by rtholmes** [comment]
Add repositories list item for provisioned repos.

**Comment by rtholmes** [comment]
Team formation is still ugly. Just a little less so.
